name: Rename LeetCode Folders

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Rename folders
        run: python rename.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Auto rename folders"
            git push
          fi
