name: Rename LeetCode Folders

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rename:
    # Prevent infinite loop on commits created by this workflow
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Rename folders
        run: python rename.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          # Get the previous commit message
          COMMIT_MSG=$(git log -1 --pretty=%B)

          echo "Using commit message:"
          echo "$COMMIT_MSG"

          # Commit using the same message
          git commit -m "${COMMIT_MSG} [skip ci]"

          git push
